config/routes.rb
Rails.application.routes.draw do
  devise_for :installs, :user
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  devise_scope :user do
   get "new_user_session", to: "devise/sessions#new"
   get "category_url", to: "devise/sessions#new"
   get '/logout',  :to => "devise/sessions#destroy"
  end

  root 'categories#index'
  #devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  #devise_for :user
  get "profile", to: "users#show"
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, uniqueness: true
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates_presence_of :title, :description, :price
  validates_format_of :price, :with => /^\d+\.?\d{0,2}$/, :multiline => true

  def average_rating
    rating_sum = reviews.map(&:rating).sum

    (rating_sum.to_f / reviews.size).round(2)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates_presence_of :content, :rating, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products
  
  validates_presence_of :firstname, :lastname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  before_action :redirect, only: [:edit, :create, :update, :new, :destroy]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  
    def category_params
      params.require(:category).permit(:name)
    end

    def redirect
      redirect_to(new_user_session_path) unless user_signed_in? && current_user.admin?
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  before_action :redirect, expect: [:edit, :update]
  before_action :redirect_edit, only: [:edit, :update]

  def index
  end

  def show
  end

  def new
  end

  def edit

  end

  def create
    self.product = Product.new(product_params)

    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    product.destroy  
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id).merge(user_id: current_user.id)
  end

  def redirect
    redirect_to(new_user_session_path) unless user_signed_in?
  end

  def redirect_edit
    unless user_signed_in? && current_user == product.user
      flash[:error] = 'You are not allowed to edit this product.'
      redirect_to(category_product_url(category, product))
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)

  def edit
  end

  def create
    self.review = Review.new(review_params)

    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
  
    def review_params
      params.require(:review).permit(:content, :rating).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!

  def show
    @user = current_user

    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save category', class: 'btn btn-default'

app/views/categories/edit.html.haml
.panel.panel-default
  .panel-heading
    .row
      %div{:class => "col-md-3"}
        %h3{:align => :up}
          %span.glyphicon.glyphicon-edit
          editing category:
          = category.name
      %div{:class => "col-md-9", :align => :right}
        = link_to 'Show category', category_products_path(category), class: 'btn btn-default'

  .panel-body
    = render 'form'

app/views/categories/index.html.haml
.panel.panel-default
  .panel-heading.panel-heading-list
    .row
      %div{:class => "col-md-3"}
        %h3{:align => :up}
          %span.glyphicon.glyphicon-home
          all categories
      %div{:class => "col-md-9", :align => :right}
        = link_to 'New Category', new_category_path, class: 'btn btn-success'
  .panel-body.panel-list
    .table-responsible
      %table.table.table-hover
        %thead
          %tr
            %th Name
            %th Products
            %th Actions
            %th
            %th
        %tbody
          - categories.each do |category|
            %tr
              %td= category.name
              %td= category.products.size
              %td= link_to 'Show', category_products_path(category)
              - if user_signed_in?
                %td= link_to 'Edit', edit_category_path(category)
                %td= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }
              - else
                %td
                %td
%br

app/views/categories/new.html.haml
.panel.panel-default
  .panel-heading
    .row
      %div{:class => "col-md-3"}
        %h3{:align => :up}
          New category
      %div{:class => "col-md-9", :align => :right}
        = link_to 'Back to list', categories_path, class: 'btn btn-primary'
  .panel-body
    = render 'form'

app/views/categories/show.html.haml
%p#notice= notice

.panel.panel-default
  .panel-heading
    .row
      %div{:class => "col-md-3"}
        %h3
          %span.glyphicon.glyphicons-check
          = category.name
      %div{:class => "col-md-9", :align => :right}
        = link_to 'Back to list', categories_path, class: 'btn btn-primary'
        = link_to 'Show category', category_products_path(category), class: 'btn btn-primary'

  .panel-body
    %p
      products in category: 
      = category.products.size

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %span.navbar-brand #{AppConfig.workshops_name}
        %div
          /     %a{:href => "#"} Page 1
          /   %li
          /     %a{:href => "#"} Page 2
          /   %li
          /     %a{:href => "#"} Page 3
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{:href => categories_path}
                %span.glyphicon.glyphicon-home
                Categories
            %li
              - if user_signed_in?
                %a{:href => profile_path}
                  %span.glyphicon.glyphicon-user
                  Profile
                %li
                  %a{"data-method" => "delete", :href => destroy_user_session_path, :rel => "nofollow"}
                    %span.glyphicon.glyphicon-log-out
                    Log-out 
              - else
                %a{:href => new_user_session_path}
                  %span.glyphicon.glyphicon-log-in
                  Log-in
          %ul.nav.navbar-nav.navbar-right
            - if signed_in? && current_user.admin?
              %p.small.navbar-text logged as Admin
    .container
      .row
        .col-lg-12
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  .col-xs-12.col-sm-10.col-sm-offset-1
    - if product.errors.any?
      #error_explanation  
        %h1= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
        %ul
          - product.errors.full_messages.each do |msg|
            %li= msg
    %br
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    %br
    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control'
    %br
    .form-group
      = f.label :price
      = f.text_field :price, class: 'form-control'
    %br
    = f.submit 'Save product', class: 'btn btn-default'
    %br
    %br

/ %br
/ %br
/ %form.form-horizontal{:role => "form"}
/   .form-group
/     %label.col-sm-3.control-label{:for => "title"} title
/     .col-sm-9
/       %input#inputProduct.form-control{:placeholder => "product's title", :type => "title"}/
/       / %p.help-block enter title of your new product
/   .form-group
/     %label.col-sm-3.control-label{:for => "description"} description
/     .col-sm-9
/       %input#inputDescription.form-control{:placeholder => "description", :type => "description"}/
/   %button.btn.btn-default{:type => "submit"} Create User

app/views/products/edit.html.haml
.panel.panel-default
  .panel-heading
    .row
      %div{:class => "col-md-3"}
        %h3{:align => :up}
          %span.glyphicon.glyphicon-edit
          editing product:
          = product.title
      %div{:class => "col-md-9", :align => :right}
        = link_to 'Back to products', category_products_path(category), class: 'btn btn-default'
        = link_to 'Show product', category_product_path(category, product), class: 'btn btn-default'
  .panel-body      
    = render 'form'

app/views/products/index.html.haml
.container
  .panel.panel-default
    .panel-heading.panel-heading-list
      .row
        %div{:class => "col-md-3"}
          %h3{:align => :up}
            %span.glyphicon.glyphicon-list-alt
            = category.name
            .small
              products from category
        %div{:class => "col-md-9", :align => :right}
          = link_to 'All categories', categories_path, class: 'btn btn-default'
          = link_to 'Edit category', edit_category_path(category), class: 'btn btn-default'
          = link_to 'New product', new_category_product_path(category), class: 'btn btn-default'
    .panel-body.panel-list
      .table-responsible
        %table.table.table-hover
          %thead
            %tr
              %th Name
              %th Description
              %th Rating
              %th Price
              %th Actions
              %th
              %th
          %tbody
            - category.products.each do |product|
              %tr
              %td= product.title
              %td= product.description
              %td= product.average_rating
              %td= product.price
              %td= link_to 'Show', category_product_path(product.category, product)
              - if signed_in?
                - if current_user.id == product.user_id || current_user.admin?
                  %td= link_to 'Edit', edit_category_product_path(product.category, product)
                  %td= link_to 'Delete', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }
                - else
                  %td
                  %td
  .panel.panel-default
    .panel-heading.panel-heading-new
      .row
        %div{:class => "col-md-3"}
          %h3
            %h3 
              %span.glyphicon.glyphicon-plus
              New product
              .small
                category:
                = category.name
              
    .panel-body
      = render 'products/form'

app/views/products/new.html.haml
.col-xs-12.col-sm-8.col-sm-offset-2
  .panel.panel-default
    .panel-heading.panel-heading-new
      .row
        %div{:class => "col-md-12"}
          %h3
            %span.glyphicon.glyphicon-plus
            New product
            .small
              category:
              = category.name
            
    .panel-body
      = render 'products/form'
  = link_to 'Back to list of products', category_products_path
  .div
    %br

app/views/products/show.html.haml
.container
  .row
    %div{:class => "col-md-12"}
      %b
        %p#notice= notice
        %p#error= flash[:error]

  .row
    %div{:class => "col-md-4"}
      .panel.panel-default
        .panel-heading.panel-heading-product        
          %h3
            %b
              = product.title
            .small
              product
        .panel-body
          %h4
            .small
              description:
            = product.description
            %p
              .small
                price:
              = product.price
            %p
              .small
                category:
              = product.category.name
            %p
              .small
                added by:
              = product.user.firstname + ' ' + product.user.lastname
              - if product.user.admin?
                (admin)
            %p
              = link_to 'Back to category', category_products_path, class: 'btn btn-default'
              = link_to 'Edit product', edit_category_product_path(category.id, product.id), class: 'btn btn-default'
            %hr
            .panel.panel-default
              .panel-body
                = render 'reviews/form'

    %div{:class => "col-md-8"}
      .panel.panel-default
        .panel-heading.panel-heading-review
          %h4 
            reviews
            .small
              average rating:
              = product.average_rating
        .panel-body.panel-list
          - if product.reviews.size == 0
            can't find any reviews of this product!
          = render reviews

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label "Add your review here:"
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Submit review', class: 'btn btn-default'

app/views/reviews/_review.html.haml
.panel.panel-default
  .panel-heading.panel-heading-review
    author:
    %b
      = review.author
    , rating:
    %b
      = review.rating
    , date:
    %b
      = review.created_at.strftime("%m/%d/%y")
  .panel-body
    = review.content
    %br
    %br

app/views/reviews/index.html.haml
%h1
  Reviews of:
  %p
    = product.title


- product.reviews.each do |rev|
  .panel.panel-default
    .panel-heading.panel-heading-review
      author:
      %b
        = User.find(rev.user_id).lastname
      , rating:
      %b
        = rev.rating
    .panel-body
      = rev.content
      %br
      %br

app/views/reviews/new.html.haml
%h1 New review of product

/ = render 'reviews/form'

app/views/users/index.html.haml
%h1 User profile

app/views/users/show.html.haml
.container
  .row
    %div{:class => "col-md-3"}
      .panel.panel-default
        .panel-heading.panel-heading-profile
          %h3 
            %span.glyphicon.glyphicon-user
            = current_user.firstname + ' ' + current_user.lastname
            .small
              - if current_user.admin?
                administrator
              - else
                normal user
        .panel-body
          .clearfix
            %h4
              .div
                = current_user.email
                .small  
                  e-mail address
              %p              
                = current_user.sign_in_count
                times
                .small
                  signed in
              %p
                = current_user.last_sign_in_ip
                .small
                  last IP
              %p
                = current_user.reviews.size
                .small
                  reviews
              %p
                = current_user.products.size
                .small
                  products
              %div{:class => "col-md-12", :align => :right}
                = link_to 'edit User', edit_user_registration_path(current_user), class: 'btn btn-default'


    %div{:class => "col-md-9"}
      .panel.panel-default
        .panel-heading.panel-heading-review
          %h4
            .text-center
              user's latest reviews
        .panel-body.panel-list
          - last_reviews = current_user.reviews.last(5)
          - last_reviews.each do |rev|
            .panel.panel-default
              .panel-heading
                product:
                %b
                  - if rev.product != nil
                    = rev.product.title
                  - else  
                    product deleted
                , rating:
                %b
                  = rev.rating
                , date:
                %b
                  = rev.created_at.strftime("%m/%d/%y")
              .panel-body
                = rev.content
                %br
                %br